/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.hirushan.microservices.order.event;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class OrderPlacedEvent extends org.apache.avro.specific.SpecificRecordBase
        implements org.apache.avro.specific.SpecificRecord {
    private static final long serialVersionUID = 8747090203382430010L;

    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse(
            "{\"type\":\"record\",\"name\":\"OrderPlacedEvent\",\"namespace\":\"com.hirushan.microservices.order.event\",\"fields\":[{\"name\":\"orderNumber\",\"type\":\"string\"},{\"name\":\"email\",\"type\":\"string\"},{\"name\":\"firstName\",\"type\":\"string\"},{\"name\":\"lastName\",\"type\":\"string\"}]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    private static final SpecificData MODEL$ = new SpecificData();

    private static final BinaryMessageEncoder<OrderPlacedEvent> ENCODER = new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

    private static final BinaryMessageDecoder<OrderPlacedEvent> DECODER = new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

    public static BinaryMessageEncoder<OrderPlacedEvent> getEncoder() {
        return ENCODER;
    }

    public static BinaryMessageDecoder<OrderPlacedEvent> getDecoder() {
        return DECODER;
    }

    public static BinaryMessageDecoder<OrderPlacedEvent> createDecoder(SchemaStore resolver) {
        return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
    }

    public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
        return ENCODER.encode(this);
    }

    public static OrderPlacedEvent fromByteBuffer(java.nio.ByteBuffer b) throws java.io.IOException {
        return DECODER.decode(b);
    }

    private CharSequence orderNumber;
    private CharSequence email;
    private CharSequence firstName;
    private CharSequence lastName;

    public OrderPlacedEvent() {
    }

    public OrderPlacedEvent(CharSequence orderNumber, CharSequence email, CharSequence firstName,
            CharSequence lastName) {
        this.orderNumber = orderNumber;
        this.email = email;
        this.firstName = firstName;
        this.lastName = lastName;
    }

    @Override
    public org.apache.avro.specific.SpecificData getSpecificData() {
        return MODEL$;
    }

    @Override
    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    @Override
    public Object get(int field$) {
        switch (field$) {
            case 0:
                return orderNumber;
            case 1:
                return email;
            case 2:
                return firstName;
            case 3:
                return lastName;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    @Override
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, Object value$) {
        switch (field$) {
            case 0:
                orderNumber = (CharSequence) value$;
                break;
            case 1:
                email = (CharSequence) value$;
                break;
            case 2:
                firstName = (CharSequence) value$;
                break;
            case 3:
                lastName = (CharSequence) value$;
                break;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    public CharSequence getOrderNumber() {
        return orderNumber;
    }

    public void setOrderNumber(CharSequence value) {
        this.orderNumber = value;
    }

    public CharSequence getEmail() {
        return email;
    }

    public void setEmail(CharSequence value) {
        this.email = value;
    }

    public CharSequence getFirstName() {
        return firstName;
    }

    public void setFirstName(CharSequence value) {
        this.firstName = value;
    }

    public CharSequence getLastName() {
        return lastName;
    }

    public void setLastName(CharSequence value) {
        this.lastName = value;
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    public static Builder newBuilder(Builder other) {
        return other == null ? new Builder() : new Builder(other);
    }

    public static Builder newBuilder(OrderPlacedEvent other) {
        return other == null ? new Builder() : new Builder(other);
    }

    @org.apache.avro.specific.AvroGenerated
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderPlacedEvent>
            implements org.apache.avro.data.RecordBuilder<OrderPlacedEvent> {

        private CharSequence orderNumber;
        private CharSequence email;
        private CharSequence firstName;
        private CharSequence lastName;

        private Builder() {
            super(SCHEMA$, MODEL$);
        }

        private Builder(Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.orderNumber)) {
                this.orderNumber = data().deepCopy(fields()[0].schema(), other.orderNumber);
                fieldSetFlags()[0] = other.fieldSetFlags()[0];
            }
            if (isValidValue(fields()[1], other.email)) {
                this.email = data().deepCopy(fields()[1].schema(), other.email);
                fieldSetFlags()[1] = other.fieldSetFlags()[1];
            }
            if (isValidValue(fields()[2], other.firstName)) {
                this.firstName = data().deepCopy(fields()[2].schema(), other.firstName);
                fieldSetFlags()[2] = other.fieldSetFlags()[2];
            }
            if (isValidValue(fields()[3], other.lastName)) {
                this.lastName = data().deepCopy(fields()[3].schema(), other.lastName);
                fieldSetFlags()[3] = other.fieldSetFlags()[3];
            }
        }

        private Builder(OrderPlacedEvent other) {
            super(SCHEMA$, MODEL$);
            if (isValidValue(fields()[0], other.orderNumber)) {
                this.orderNumber = data().deepCopy(fields()[0].schema(), other.orderNumber);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.email)) {
                this.email = data().deepCopy(fields()[1].schema(), other.email);
                fieldSetFlags()[1] = true;
            }
            if (isValidValue(fields()[2], other.firstName)) {
                this.firstName = data().deepCopy(fields()[2].schema(), other.firstName);
                fieldSetFlags()[2] = true;
            }
            if (isValidValue(fields()[3], other.lastName)) {
                this.lastName = data().deepCopy(fields()[3].schema(), other.lastName);
                fieldSetFlags()[3] = true;
            }
        }

        public CharSequence getOrderNumber() {
            return orderNumber;
        }

        public Builder setOrderNumber(CharSequence value) {
            validate(fields()[0], value);
            this.orderNumber = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        public boolean hasOrderNumber() {
            return fieldSetFlags()[0];
        }

        public Builder clearOrderNumber() {
            orderNumber = null;
            fieldSetFlags()[0] = false;
            return this;
        }

        public CharSequence getEmail() {
            return email;
        }

        public Builder setEmail(CharSequence value) {
            validate(fields()[1], value);
            this.email = value;
            fieldSetFlags()[1] = true;
            return this;
        }

        public boolean hasEmail() {
            return fieldSetFlags()[1];
        }

        public Builder clearEmail() {
            email = null;
            fieldSetFlags()[1] = false;
            return this;
        }

        public CharSequence getFirstName() {
            return firstName;
        }

        public Builder setFirstName(CharSequence value) {
            validate(fields()[2], value);
            this.firstName = value;
            fieldSetFlags()[2] = true;
            return this;
        }

        public boolean hasFirstName() {
            return fieldSetFlags()[2];
        }

        public Builder clearFirstName() {
            firstName = null;
            fieldSetFlags()[2] = false;
            return this;
        }

        public CharSequence getLastName() {
            return lastName;
        }

        public Builder setLastName(CharSequence value) {
            validate(fields()[3], value);
            this.lastName = value;
            fieldSetFlags()[3] = true;
            return this;
        }

        public boolean hasLastName() {
            return fieldSetFlags()[3];
        }

        public Builder clearLastName() {
            lastName = null;
            fieldSetFlags()[3] = false;
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public OrderPlacedEvent build() {
            try {
                OrderPlacedEvent record = new OrderPlacedEvent();
                record.orderNumber = fieldSetFlags()[0] ? this.orderNumber : (CharSequence) defaultValue(fields()[0]);
                record.email = fieldSetFlags()[1] ? this.email : (CharSequence) defaultValue(fields()[1]);
                record.firstName = fieldSetFlags()[2] ? this.firstName : (CharSequence) defaultValue(fields()[2]);
                record.lastName = fieldSetFlags()[3] ? this.lastName : (CharSequence) defaultValue(fields()[3]);
                return record;
            } catch (org.apache.avro.AvroMissingFieldException e) {
                throw e;
            } catch (Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumWriter<OrderPlacedEvent> WRITER$ = (org.apache.avro.io.DatumWriter<OrderPlacedEvent>) MODEL$
            .createDatumWriter(SCHEMA$);

    @Override
    public void writeExternal(java.io.ObjectOutput out) throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumReader<OrderPlacedEvent> READER$ = (org.apache.avro.io.DatumReader<OrderPlacedEvent>) MODEL$
            .createDatumReader(SCHEMA$);

    @Override
    public void readExternal(java.io.ObjectInput in) throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }

    @Override
    protected boolean hasCustomCoders() {
        return true;
    }

    @Override
    public void customEncode(org.apache.avro.io.Encoder out) throws java.io.IOException {
        out.writeString(this.orderNumber);
        out.writeString(this.email);
        out.writeString(this.firstName);
        out.writeString(this.lastName);
    }

    @Override
    public void customDecode(org.apache.avro.io.ResolvingDecoder in) throws java.io.IOException {
        org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
        if (fieldOrder == null) {
            this.orderNumber = in.readString(this.orderNumber instanceof Utf8 ? (Utf8) this.orderNumber : null);
            this.email = in.readString(this.email instanceof Utf8 ? (Utf8) this.email : null);
            this.firstName = in.readString(this.firstName instanceof Utf8 ? (Utf8) this.firstName : null);
            this.lastName = in.readString(this.lastName instanceof Utf8 ? (Utf8) this.lastName : null);
        } else {
            for (int i = 0; i < 4; i++) {
                switch (fieldOrder[i].pos()) {
                    case 0:
                        this.orderNumber = in
                                .readString(this.orderNumber instanceof Utf8 ? (Utf8) this.orderNumber : null);
                        break;
                    case 1:
                        this.email = in.readString(this.email instanceof Utf8 ? (Utf8) this.email : null);
                        break;
                    case 2:
                        this.firstName = in.readString(this.firstName instanceof Utf8 ? (Utf8) this.firstName : null);
                        break;
                    case 3:
                        this.lastName = in.readString(this.lastName instanceof Utf8 ? (Utf8) this.lastName : null);
                        break;
                    default:
                        throw new java.io.IOException("Corrupt ResolvingDecoder.");
                }
            }
        }
    }
}
